{
 "title": "mlops-ai-app",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests to Model Server",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    { "expr": "model_requests_total", "legendFormat": "__auto" },
    { "expr": "rate(model_requests_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Model Server Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(model_request_latency_seconds_count[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(model_request_latency_seconds_sum[1m]) / rate(model_request_latency_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Model Server Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 0 },
   "targets": [
    { "expr": "model_request_errors_total", "legendFormat": "__auto" },
    {
     "expr": "rate(model_request_errors_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests to Backend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    { "expr": "api_requests_total", "legendFormat": "__auto" },
    { "expr": "rate(api_requests_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Backend Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(api_request_latency_seconds_count[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(api_request_latency_seconds_sum[1m]) / rate(api_request_latency_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (cpu) (rate(node_cpu_seconds_total{mode=~\"system|user\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum((rate(node_cpu_seconds_total{mode=~\"system|user\"}[1m])))",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Installed" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_SwapTotal_bytes", "legendFormat": "Swap" }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device!=\"lo\"}[1m])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device!=\"lo\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Available Disk Storage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(device) (node_filesystem_avail_bytes{device!~\"none|rootfs\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * max by (device) (node_filesystem_avail_bytes{device!~\"rootfs|none\"} / node_filesystem_size_bytes{device!~\"rootfs|none\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read Activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Write Activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}