version: "3.7"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - external-network
    ports:
      - "9090:9090"  # Prometheus web UI
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  # Prometheus config
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-1
    networks:
      - external-network
    ports:
      - "3000:3000"  # Grafana web UI
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: always


networks:
  external-network:
    external: true
