global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:9000']

  - job_name: 'model-server'
    static_configs:
      - targets: ['model-proxy:8000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['172.29.11.168:9100']
